export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //bottom container
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
